### PR TITLE
Added aggregate methods  

### PR DESCRIPTION
**Pull request by StemateF**
Hi there, 

I added missing aggregate functions.

Unfortunately I will need some help with the tests, I couldn't figure out how the whole test setup actually works :cry:.

@alexzarbn Please let me know what you think, if you have suggestions on improving this.

Thanks

### CODE REVIEW

**Comment by StemateF** [comment]
@alexzarbn Done. 
I also fixed a typing issue on the new type I created (oops :sweat_smile: )
Added some basic testing following the test you referenced. 
Let me know if there are more changes required, will be happy to make them.

**Comment by alexzarbn** [comment]
Hi @StemateF,

Awesome, looking great! One change is required before I merge this - TS complains about missing information in runtime.

Screenshot 2024-01-07 at 11 23 56

**Comment by StemateF** [comment]
Hi @alexzarbn, I've addressed the TypeScript errors in the code, funny enough I had to update my ts for the errors to come up on my end.

Additionally, I have included types for the `.with()` method. Please note that this might be a breaking change, as it could disrupt builds when attempting to include a relation that hasn't been defined. Similarly, trying to include a nested relation with a depth greater than 2 (e.g., `users.posts.tags`) will not work; only `users.posts` will be valid.

I'm open to increasing the depth to a larger value if needed, but implementing recursion could pose challenges. This is particularly true when two models reference each other, resulting in a scenario where the type becomes something like `users.posts.user.posts.user...`. Handling this recursive situation may be intricate. Let me know your thoughts on these changes.

**Comment by alexzarbn** [comment]
@StemateF Thank you for the quick update! 

I would suggest not to introduce breaking changes for now and leave the `with` method as is and just have the types working for the aggregates. 

Also, I'm not sure if using `string & keyof Relations` construct would actually preserve the type string in the runtime, were you able to confirm it works?

**Comment by StemateF** [comment]
Now that i look at this, I realized that the new methods will suffer from the same issue I highlighted in my previous comment "https://github.com/tailflow/laravel-orion-ts/pull/42#issuecomment-1880035754". 

Might be best to just give up on types for the relations names as it might be limiting for some users.

**Comment by alexzarbn** [comment]
@StemateF What I mean is the js output that, when used, might not work correctly, since it does not have the type information.

I will merge it as is, and will see, if any issues pop up.

**Comment by StemateF** [comment]
@alexzarbn Sounds good, thanks. Is there a planned release for the new version of the sdk on NPM ?

**Comment by alexzarbn** [comment]
> @alexzarbn Sounds good, thanks. Is there a planned release for the new version of the sdk on NPM ?

Published v4.1.0 just now

**Pull request merged**
