### PR TITLE
Batch integration

### PR DESCRIPTION
**Pull request by Alpha1337k**
Hi there,

I created a class for batch operations. Includes all routes, and supports id's for delete / restore.

Also tried to make some tests, but not sure if the quality is upto spec.

Please let me know what you think + need for improvements.

Thanks,

### CODE REVIEW

**Comment by Alpha1337k** [comment]
Hi @alexzarbn were you able to take a look?

**Comment by alexzarbn** [comment]
Hello @Alpha1337k,

Thank you for the PR. Please update it in a way how operations are implemented in the `/src/drivers/default/queryBuilder.ts`, instead of introducing a dedicated class.

**Comment by Alpha1337k** [comment]
Do you mean like `Post.$query().batchStore([])` or like `Post.$batch().store([])`? I don't envision the first one well, since I think about Batch as an overlaying entity, and not as a "`Post`", or else. Also, both have the issue where they can be called on an existing variable: `item.$query().batchStore([item1,item2 ...])` What to do in this case?

Let me know your thoughts.

**Comment by alexzarbn** [comment]
Yes, I mean like `Post.$query().batchStore([])` - it follows the current structure of other operations.

**Comment by Alpha1337k** [comment]
@alexzarbn Should be better now. Take a look.

**Comment by alexzarbn** [comment]
Awesome, thank you! Merging ~

**Pull request merged**
